# Generated by Django 5.0.2 on 2024-03-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='password',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='password',
        ),
    ]
