# Generated by Django 5.0.2 on 2024-03-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobseeker_image_recruiter_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
