# Generated by Django 5.0.2 on 2024-03-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_remove_jobseeker_password_remove_recruiter_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='password',
            field=models.CharField(default='Jobs123!', max_length=200),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='password',
            field=models.CharField(default='Jobs123!', max_length=200),
        ),
    ]
