# Generated by Django 5.0.2 on 2024-03-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_jobseeker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
