# Generated by Django 5.0.2 on 2024-03-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jobseeker_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recruiter'),
        ),
    ]
