# Generated by Django 5.0.2 on 2024-03-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_recruiter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='image',
            field=models.ImageField(null=True, upload_to='recruiter'),
        ),
    ]
