# Generated by Django 5.0.2 on 2024-03-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_experience_alter_job_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salary',
            new_name='maximum_salary',
        ),
        migrations.AddField(
            model_name='job',
            name='minium_salary',
            field=models.CharField(default='Not Disclosed', max_length=45, null=True),
        ),
    ]
