# Generated by Django 5.0.2 on 2024-03-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_rename_salary_job_maximum_salary_job_minium_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='rate',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
