# Generated by Django 5.0.2 on 2024-03-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_job_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='minium_salary',
            new_name='minimum_salary',
        ),
    ]
