# Generated by Django 5.0.2 on 2024-03-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_rename_minium_salary_job_minimum_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
