# Generated by Django 5.0.2 on 2024-03-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_job_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='maximum_salary',
            field=models.CharField(default='Not Disclosed', max_length=45),
        ),
        migrations.AlterField(
            model_name='job',
            name='minimum_salary',
            field=models.CharField(default='Not Disclosed', max_length=45),
        ),
        migrations.AlterField(
            model_name='job',
            name='rate',
            field=models.CharField(max_length=10),
        ),
    ]
