# Generated by Django 5.0.2 on 2024-03-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_alter_job_maximum_salary_alter_job_minimum_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default='request pending', max_length=20),
        ),
    ]
