# Generated by Django 5.0.2 on 2024-03-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(blank=True, default='none', null=True, upload_to='user_resume'),
        ),
    ]
