# Generated by Django 5.0.4 on 2024-04-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_alter_jobseeker_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='maximum_salary',
        ),
    ]
