# Generated by Django 5.0.4 on 2024-04-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_application_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recruiter'),
        ),
    ]
