# Generated by Django 5.0.4 on 2024-04-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_alter_recruiter_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='location',
            field=models.CharField(blank=True, default='not updated', max_length=100, null=True),
        ),
    ]
